blank_issues_enabled: false

contact_links:
  - name: Feature request
    url: https://github.com/AsnySprite/AsnySprite-proposals/issues/
    about: Please submit feature proposals and discussions (meta and not) on the AsnySprite proposals repository
